## name: Lumon

foreground              #d6e2ee
background              #16242d
selection_foreground    #1b2d40
selection_background    #4d9ed3

cursor                  #f2fcff
cursor_text_color       #16242d

url_color               #b4e4f6

active_border_color     #6fb8e3
inactive_border_color   #304860
bell_border_color       #6fa4c9

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #d6e2ee
active_tab_background   #6fb8e3
inactive_tab_foreground #304860
inactive_tab_background #16242d
tab_bar_background      #1b2d40

mark1_foreground        #16242d
mark1_background        #6fb8e3
mark2_foreground        #16242d
mark2_background        #5e95bc
mark3_foreground        #16242d
mark3_background        #b4e4f6

color0  #1b2d40
color8  #304860
color1  #4d86b0
color9  #73a6cb
color2  #5e95bc
color10 #86b7d8
color3  #6fa4c9
color11 #9dcae5
color4  #6fb8e3
color12 #f2fcff
color5  #8bc9eb
color13 #b1d8ee
color6  #b4e4f6
color14 #d1eef8
color7  #d6e2ee
color15 #ffffff
