## name: White

foreground              #000000
background              #ffffff
selection_foreground    #ffffff
selection_background    #1a1a1a

cursor                  #000000
cursor_text_color       #ffffff

url_color               #3e3e3e

active_border_color     #6e6e6e
inactive_border_color   #c0c0c0
bell_border_color       #4a4a4a

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #000000
active_tab_background   #ffffff
inactive_tab_foreground #c0c0c0
inactive_tab_background #ffffff
tab_bar_background      #ffffff

mark1_foreground        #ffffff
mark1_background        #1a1a1a
mark2_foreground        #ffffff
mark2_background        #3a3a3a
mark3_foreground        #ffffff
mark3_background        #3e3e3e

color0  #ffffff
color8  #c0c0c0
color1  #2a2a2a
color9  #2a2a2a
color2  #3a3a3a
color10 #3a3a3a
color3  #4a4a4a
color11 #4a4a4a
color4  #1a1a1a
color12 #1a1a1a
color5  #2e2e2e
color13 #2e2e2e
color6  #3e3e3e
color14 #3e3e3e
color7  #000000
color15 #000000
