## name: Retro 82

foreground              #f6dcac
background              #05182e
selection_foreground    #303442
selection_background    #faa968

cursor                  #f6dcac
cursor_text_color       #05182e

url_color               #8cbfb8

active_border_color     #faa968
inactive_border_color   #134e5a
bell_border_color       #e97b3c

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #f6dcac
active_tab_background   #05182e
inactive_tab_foreground #134e5a
inactive_tab_background #05182e
tab_bar_background      #00172e

mark1_foreground        #05182e
mark1_background        #faa968
mark2_foreground        #05182e
mark2_background        #028391
mark3_foreground        #05182e
mark3_background        #8cbfb8

color0  #303442
color8  #134e5a
color1  #f85525
color9  #f85525
color2  #028391
color10 #028391
color3  #e97b3c
color11 #e97b3c
color4  #faa968
color12 #faa968
color5  #3f8f8a
color13 #3f8f8a
color6  #8cbfb8
color14 #8cbfb8
color7  #a7c9c6
color15 #f6dcac
