{
  "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
  "name": "omarchy-system",
  "vars": {
    "background": "{{ bg }}",
    "foreground": "{{ fg }}",
    "accent": "{{ accent }}",
    "selectionBackground": "{{ selection_background }}",
    "selectionForeground": "{{ selection_foreground }}",
    "selectedBackground": "{{ mix bg accent 22% }}",
    "color0": "{{ bg }}",
    "color1": "{{ red }}",
    "color2": "{{ green }}",
    "color3": "{{ yellow }}",
    "color4": "{{ blue }}",
    "color5": "{{ magenta }}",
    "color6": "{{ cyan }}",
    "color7": "{{ fg }}",
    "color8": "{{ muted }}",
    "color9": "{{ bright_red }}",
    "color10": "{{ bright_green }}",
    "color11": "{{ bright_yellow }}",
    "color12": "{{ bright_blue }}",
    "color13": "{{ bright_magenta }}",
    "color14": "{{ bright_cyan }}",
    "color15": "{{ bright_fg }}",
    "panel": "{{ mix bg fg 6% }}",
    "panelAlt": "{{ mix bg fg 10% }}",
    "panelPending": "{{ mix bg accent 12% }}",
    "panelSuccess": "{{ mix bg green 12% }}",
    "panelError": "{{ mix bg red 12% }}",
    "border": "{{ mix bg fg 30% }}",
    "borderMuted": "{{ mix bg fg 20% }}",
    "mutedText": "{{ mix fg bg 34% }}",
    "dimText": "{{ mix fg bg 52% }}"
  },
  "colors": {
    "accent": "accent",
    "border": "border",
    "borderAccent": "accent",
    "borderMuted": "borderMuted",
    "success": "color2",
    "error": "color1",
    "warning": "color3",
    "muted": "mutedText",
    "dim": "dimText",
    "text": "foreground",
    "thinkingText": "dimText",
    "selectedBg": "selectedBackground",
    "userMessageBg": "panel",
    "userMessageText": "foreground",
    "customMessageBg": "panel",
    "customMessageText": "foreground",
    "customMessageLabel": "accent",
    "toolPendingBg": "panelPending",
    "toolSuccessBg": "panelSuccess",
    "toolErrorBg": "panelError",
    "toolTitle": "accent",
    "toolOutput": "foreground",
    "mdHeading": "color5",
    "mdLink": "accent",
    "mdLinkUrl": "color6",
    "mdCode": "color6",
    "mdCodeBlock": "foreground",
    "mdCodeBlockBorder": "borderMuted",
    "mdQuote": "mutedText",
    "mdQuoteBorder": "borderMuted",
    "mdHr": "borderMuted",
    "mdListBullet": "color5",
    "toolDiffAdded": "color2",
    "toolDiffRemoved": "color1",
    "toolDiffContext": "mutedText",
    "syntaxComment": "dimText",
    "syntaxKeyword": "color5",
    "syntaxFunction": "color4",
    "syntaxVariable": "accent",
    "syntaxString": "color2",
    "syntaxNumber": "color3",
    "syntaxType": "color4",
    "syntaxOperator": "color5",
    "syntaxPunctuation": "mutedText",
    "thinkingOff": "borderMuted",
    "thinkingMinimal": "accent",
    "thinkingLow": "color4",
    "thinkingMedium": "color5",
    "thinkingHigh": "color3",
    "thinkingXhigh": "color1",
    "bashMode": "color3"
  },
  "export": {
    "pageBg": "{{ bg }}",
    "cardBg": "{{ mix bg fg 6% }}",
    "infoBg": "{{ mix bg fg 10% }}"
  }
}
